modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (31 is current forge version for 1.15.2)
issueTrackerURL="https://github.com/CodenameRevy/Flesh2Leather/issues" #optional
[[mods]] #mandatory
modId="f2l" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Flesh 2 Leather" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/CodenameRevy/Flesh2Leather" #optional
logoFile="logo.png" #optional
credits="CodenameRevy" #optional
authors="CodenameRevy" #optional
description='''
This Mod adds a new Item called "Combined Flesh" that can be smoked into Leather!
'''
[[dependencies.f2l]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.f2l]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
