modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/CodenameRevy/Flesh2Leather/issues" #optional
[[mods]] #mandatory
modId="flesh2leather" #mandatory
version="1.0.1" #mandatory
displayName="Flesh 2 Leather" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/CodenameRevy/Flesh2Leather" #optional
logoFile="logo.png" #optional
credits="CodenameRevy" #optional
authors="CodenameRevy" #optional
description='''
This Mod adds a new Item called "Combined Flesh" that can be smoked into Leather!
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
